import { ArrowDown, ArrowRight, CalendarClock, CheckCircle2, CircleMinus, FileSearch, GitPullRequest, Scale, ShieldCheck } from 'lucide-react'
import { Link } from 'react-router-dom'
import { PageHeader, SourceLinks } from '../components/Shared'
import { sources } from '../data/sources'
import { ui } from '../i18n/en'

const vtPolicyIds = ['vt-approved-tools', 'vt-hokieai', 'vt-risk', 'vt-ferpa', 'vt-research-ai', 'vt-ai-principles', 'vt-teaching-ai', 'vt-microsoft-copilot']
const privacySecurityIds = ['openai-privacy', 'anthropic-privacy', 'perplexity-files', 'notebooklm-privacy', 'gemini-privacy']
const vendorCapabilityIds = sources.map((source) => source.id).filter((id) => !vtPolicyIds.includes(id) && !privacySecurityIds.includes(id))

export function MethodologyPage() {
  return (
    <>
      <PageHeader {...ui.pageHeaders.methodology} />
      <section className="container method-flow" aria-labelledby="method-flow-title">
        <h2 id="method-flow-title" className="sr-only">Recommendation sequence</h2>
        <div><span>01</span><ShieldCheck /><h3>Safety boundary</h3><p>Stop unknown classifications. Remove account contexts outside the selected data boundary.</p></div><ArrowDown className="flow-arrow" /><div><span>02</span><Scale /><h3>Capability fit</h3><p>Map documented task fit, inputs, outputs, web, sources, files, code, work setting, ecosystem, and access.</p></div><ArrowDown className="flow-arrow" /><div><span>03</span><FileSearch /><h3>Explain differences</h3><p>Show fit bands, limitations, safety exclusions, and an optional point-by-point calculation.</p></div><ArrowDown className="flow-arrow" /><div><span>04</span><CheckCircle2 /><h3>Human handoff</h3><p>Select a workflow skill and name what a person must verify, decide, and approve.</p></div>
      </section>
      <section className="method-sections section"><div className="container two-column-content">
        <article><p className="eyebrow">Recommendation rules</p><h2>What changes the result</h2><ul className="check-list"><li>Four task-fit levels describe documented feature alignment, not measured output quality.</li><li>Strong citation workflows receive emphasis only when a source trail is required.</li><li>Products receive deductions when a required file, web, code, collaboration mode, or account condition is missing.</li><li>Close results are explicitly presented as a conditional choice.</li><li>No eligible result triggers a human-only or locally approved path.</li></ul><Link to="https://github.com/meizisong888/LIB_showcase/blob/main/src/data/recommendationRules.ts" target="_blank">Inspect the transparent weights <ArrowRight size={15} /></Link></article>
        <article><p className="eyebrow">Content inclusion</p><h2>Why these tools and skills</h2><ul className="check-list"><li>Eight products cover general assistants, web research, source-grounded learning, Microsoft/Google work, university-protected access, and coding.</li><li>Every decision-relevant claim needs a first-party product, formal research, or Virginia Tech source.</li><li>Every entry has use and non-use boundaries, sources, and a review date.</li><li>Installable entries require publisher, official source, license, platforms, permissions, maintenance, and security notes.</li><li>Popularity and vendor benchmarks are not inclusion or ranking criteria.</li></ul></article>
        <article><p className="eyebrow">Skill evaluation</p><h2>What “verified” means here</h2><p>Verified means the structured record passes this project’s evidence and completeness checks as of the shown date. It does not certify safety, output quality, accessibility, or VT approval.</p><ul className="check-list"><li>Source exists and directly relates to the recorded capability.</li><li>Prompt, inputs, steps, failure modes, and checks form a reproducible workflow.</li><li>Permission-bearing skills disclose the practical access surface.</li><li>A missing source or review date automatically downgrades display status to Needs review.</li></ul></article>
        <article><p className="eyebrow">Source hierarchy</p><h2>Evidence tiers</h2><dl className="tier-definitions"><div><dt>Official</dt><dd>VT policy/guidance or the product publisher’s own current documentation.</dd></div><div><dt>Curated</dt><dd>A workflow judgment assembled from declared sources and review criteria.</dd></div><div><dt>Community</dt><dd>A discoverable lead requiring independent provenance, permissions, and maintenance checks.</dd></div></dl></article>
      </div></section>
      <section className="container section update-process"><div className="section-heading"><p className="eyebrow">Update process</p><h2>Facts have an expiration path</h2></div><div className="update-grid"><article><CalendarClock /><h3>Review</h3><p>Re-open sources, inspect dates and product/account boundaries, and record the review date.</p></article><article><CircleMinus /><h3>Downgrade</h3><p>Mark Needs review when evidence is missing or ambiguous; mark Outdated when a claim is contradicted.</p></article><article><GitPullRequest /><h3>Change in public</h3><p>Submit the source, affected claim, applicability boundary, and verification date through a structured issue.</p></article></div></section>
      <section className="limitations-section section"><div className="container"><div><p className="eyebrow">Known limitations</p><h2>What this MVP does not know</h2></div><ul><li>It cannot determine the true sensitivity of your files.</li><li>It does not inspect your license, administrator settings, contract, course rules, IRB, or data-use agreement.</li><li>It does not benchmark model quality or guarantee feature availability.</li><li>It does not install skills, call paid models, or send form answers to a server.</li><li>It reflects sources reviewed on August 28, 2026; live official pages remain authoritative.</li></ul></div></section>
      <section className="container section source-catalog"><div className="section-heading split-heading"><div><p className="eyebrow">Source register</p><h2>{sources.length} first-party references</h2></div><p>Claim scope is recorded so a link is not treated as support for facts it does not cover.</p></div><div className="source-register-groups"><details open><summary>VT policy & guidance ({vtPolicyIds.length})</summary><SourceLinks sourceIds={vtPolicyIds} compact /></details><details><summary>Vendor capability documentation ({vendorCapabilityIds.length})</summary><SourceLinks sourceIds={vendorCapabilityIds} compact /></details><details><summary>Privacy & security documentation ({privacySecurityIds.length})</summary><SourceLinks sourceIds={privacySecurityIds} compact /></details></div></section>
    </>
  )
}
