import { Accessibility, ArrowRight, BookOpenCheck, Check, CircleHelp, DatabaseZap, ExternalLink, FileWarning, GraduationCap, ScanSearch, ShieldAlert, UserCheck } from 'lucide-react'
import { Link } from 'react-router-dom'
import { PageHeader, SafetyCallout, SourceLinks } from '../components/Shared'
import { ui } from '../i18n/en'

const safetyTopics = [
  { icon: GraduationCap, title: 'FERPA & student records', text: 'Education records and personally identifying student data require authorized access and appropriate handling. Most FERPA-protected data is moderate risk in the current VT standard; some combinations or contexts may be higher.', actions: ['Minimize identifiers before processing.', 'Use only the correct VT-approved instance for the data level.', 'Do not infer that a student’s use of AI permits reuse of their work or data.'] },
  { icon: DatabaseZap, title: 'Unpublished & human-subject research', text: 'Data-use agreements, consent, IRB terms, sponsor rules, export controls, and re-identification risk can limit AI use even when a platform is approved for high-risk data.', actions: ['Ask the PI and review the protocol or agreement.', 'Prefer synthetic or minimized data for exploration.', 'Contact PRDP, IRB, or export-control specialists when applicable.'] },
  { icon: BookOpenCheck, title: 'Academic integrity & disclosure', text: 'Appropriate AI use depends on the course, assignment, discipline, publisher, and audience. Students need specific instructor guidance; authors remain accountable for submitted work.', actions: ['Follow assignment-specific directions.', 'Document material AI assistance when required.', 'Never rely on AI to determine whether its own use is permitted.'] },
  { icon: ScanSearch, title: 'Hallucinations, citations & recency', text: 'A fluent answer, working link, or citation marker can still be wrong, incomplete, or out of date. AI cannot transfer accountability to a source badge.', actions: ['Open the primary source.', 'Check sentence-level support and publication date.', 'Recalculate quantities and verify quoted text.'] },
  { icon: UserCheck, title: 'Human review & consequential decisions', text: 'AI should extend human judgment—not replace the accountable person. Grading, hiring, discipline, research conclusions, policy, and high-impact administrative decisions need qualified human review.', actions: ['Name the accountable reviewer.', 'Provide a non-AI path when appropriate.', 'Record uncertainty, disagreement, and override.'] },
  { icon: Accessibility, title: 'Accessibility & fairness', text: 'Generated content can reproduce stereotypes or create barriers. Automated review can help find issues but cannot certify accessibility or substitute for affected users.', actions: ['Test keyboard, reflow, contrast, media alternatives, and assistive technology.', 'Review examples, labels, and outcomes for disparate effects.', 'Include affected people in evaluation.'] },
  { icon: FileWarning, title: 'Third-party skills & supply chain', text: 'Installing a skill can expose files, commands, network traffic, accounts, and secrets. A trusted host does not automatically make every marketplace item trustworthy.', actions: ['Verify publisher, source, license, and maintenance.', 'Map direct and transitive permissions.', 'Test with low-risk data in an isolated, reversible environment.'] },
]

export function SafetyPage() {
  return (
    <>
      <PageHeader {...ui.pageHeaders.safety} />
      <section className="container data-class-section">
        <div className="section-heading split-heading"><div><p className="eyebrow">Plain-language triage</p><h2>What kind of information are you handling?</h2></div><p>These three cards are a usability layer. Virginia Tech’s authoritative standard uses Low, Moderate, and High Risk; classify mixed data at the highest applicable level.</p></div>
        <div className="data-class-grid">
          <article className="data-public"><span>Public</span><h3>Intended for open access</h3><p>Published pages, public procedures, and unrestricted research intended for public distribution.</p><strong><Check size={16} />Still minimize personal data</strong></article>
          <article className="data-internal"><span>Internal</span><h3>Not intended for everyone</h3><p>Internal communications, nonpublic reports, contracts, most FERPA-protected records, and unpublished information may be moderate risk.</p><strong><ShieldAlert size={16} />Use an approved account boundary</strong></article>
          <article className="data-restricted"><span>Restricted</span><h3>Sensitive, regulated, or high impact</h3><p>SSNs, credentials, export-controlled data, some health and human-subject data, or information governed by contract can be high risk.</p><strong><FileWarning size={16} />Additional controls may apply</strong></article>
          <article className="data-unknown"><span>Unknown</span><h3>Classification is unclear</h3><p>If a type is not listed or permissions are uncertain, do not guess based on the file name or whether it is “de-identified.”</p><strong><CircleHelp size={16} />Stop and ask the data owner</strong></article>
        </div>
      </section>
      <section className="section safety-boundary"><div className="container"><SafetyCallout title="An approved tool is not blanket permission"><p>Virginia Tech’s current approved-tools page lists data-risk levels and account requirements. Use the correct VT login instance, minimize data, and confirm additional rules. The official page specifically notes that some high-risk data—including data governed by DFARS or ITAR—may need protections beyond a general high-risk approval.</p><a href="https://ai.vt.edu/tools.html" target="_blank" rel="noreferrer">Check the live VT approved-tools list <ExternalLink size={15} /></a></SafetyCallout></div></section>
      <section className="container section safety-topics"><div className="section-heading"><p className="eyebrow">Seven review lenses</p><h2>Responsible use is more than privacy</h2></div><div className="safety-topic-grid">{safetyTopics.map((topic) => { const Icon = topic.icon; return <article key={topic.title}><Icon aria-hidden="true" /><h3>{topic.title}</h3><p>{topic.text}</p><ul>{topic.actions.map((action) => <li key={action}>{action}</li>)}</ul></article> })}</div></section>
      <section className="container uncertainty-section"><div><p className="eyebrow">When the answer is unclear</p><h2>Use this stop rule</h2><blockquote>“I cannot confirm that this data, account, and use are permitted. I will not upload it until the official owner or policy confirms the boundary.”</blockquote></div><div className="uncertainty-actions"><h3>Then check</h3><ol><li>VT Risk Classification Standard</li><li>VT’s current approved-tools page</li><li>Data steward, instructor, PI, contract, IRB, or security owner</li><li>The exact product account and sharing settings</li></ol><Link to="/recommend" className="button">Return to task finder <ArrowRight size={18} /></Link></div></section>
      <section className="container section safety-sources"><SourceLinks sourceIds={['vt-approved-tools', 'vt-risk', 'vt-ferpa', 'vt-research-ai', 'vt-teaching-ai', 'vt-ai-principles']} /></section>
    </>
  )
}
